import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

// Obsidian only auto-loads styles.css from the plugin folder, but esbuild
// emits the bundled stylesheet as main.css. Mirror it after every build so
// the dev loop picks up CSS without a manual rename.
const mirrorStylesheet = () => {
	if (fs.existsSync("main.css")) {
		fs.copyFileSync("main.css", "styles.css");
	}
};

esbuild
	.build({
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/closebrackets",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/comment",
			"@codemirror/fold",
			"@codemirror/gutter",
			"@codemirror/highlight",
			"@codemirror/history",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/matchbrackets",
			"@codemirror/panel",
			"@codemirror/rangeset",
			"@codemirror/rectangular-selection",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/stream-parser",
			"@codemirror/text",
			"@codemirror/tooltip",
			"@codemirror/view",
			...builtins,
		],
		format: "cjs",
		watch: prod
			? false
			: {
					onRebuild(error) {
						if (error) {
							console.error("esbuild rebuild failed:", error);
							return;
						}
						mirrorStylesheet();
					},
			  },
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile: "main.js",
	})
	.then(mirrorStylesheet)
	.catch(() => process.exit(1));
